name: reporter_app
description: Family Tracker Reporter App
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  tracker_core:
    path: ../../packages/tracker_core

  dio: ^5.5.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.4
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
